POST http://localhost:8080/api/auth
Content-Type: application/json

{
  "email": "teste@teste.com",
  "password": "123456"
}

###
GET http://localhost:8080/api/produtos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzM5MWEwYWVmNjk5MjgxNWFjOWUxYiIsImlhdCI6MTc0MDg3MDg3MSwiZXhwIjoxNzQzNDYyODcxfQ.NU9GOV_fGMiB56RtA_PNj1SFqC2c3_9CBWfn1nbSLHk


###
POST http://localhost:8080/api/produtos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzM5MWEwYWVmNjk5MjgxNWFjOWUxYiIsImlhdCI6MTc0MDg3MDg3MSwiZXhwIjoxNzQzNDYyODcxfQ.NU9GOV_fGMiB56RtA_PNj1SFqC2c3_9CBWfn1nbSLHk
Content-Type: application/json

{
  "nome": "Bacia de Pipoca",
  "preco": 2.99
}

###
PUT http://localhost:8080/api/produtos/651a2ccf-c7e8-4b61-b042-3f9710e16343
Content-Type: application/json

{
  "nome": "Copo de Whiskey",
  "preco": 15.99
}

###
DELETE http://localhost:8080/api/produtos/efa84fc5-a1da-4950-a9b6-2b99f91e965d