POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "teste2@teste.com",
  "fullName": "Teste2 Teste",
  "password": "1234561"
}


###
GET http://localhost:8080/api/auth


###
POST http://localhost:8080/api/auth
Content-Type: application/json

{
  "email": "teste2@teste.com",
  "password": "1234561"
}